---
site_name: "analysis-api-schema"
theme:
  name: material
  palette:
   scheme: slate
   primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
  # - mknotebooks:  # install mknotebooks if needed for notebook rendering
  #     execute: false
  - mermaid2:
      version: 11.4.1
  # TODO rebuild docs on schema change (https://github.com/dalito/linkml-project-copier/issues/39)
  # - gen-files:
  #     scripts:
  #       - gen_pages.py  # or any other name or path

# watch:
#   - src/test_linkml/schema

nav:
  - Home: index.md
  - Schema: elements/index.md
  - About: about.md

exclude_docs: |
  /templates-linkml/

site_url: https://my-org.github.io/test-linkml
repo_url: https://github.com/my-org/test-linkml

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
