[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[project]
name = "analysis_api_schema"
description = "linkML transition for analysis-api schemas"
authors = [
  {name = "Maia Kapur", email = "maia.kapur@pnnl.gov"},
  {name = "Conrad Mearns", email = "conrad.mearns@pnnl.gov"},
  {name = "Montana Smith", email = "montana.smith@pnnl.gov"},
]

# TODO: legal will require review
# license = "MIT"
# license-files = ["LICENSE"]

readme = "README.md"
requires-python = ">=3.9,<4.0"
dynamic = ["version"]

dependencies = [
#   "linkml-runtime >=1.9.4",
    "linkml==1.9.1",
]

[dependency-groups]
dev = [
    # "linkml>=1.9.1",
    "mkdocs-material>=8.2.8",
    "mkdocs-mermaid2-plugin>=1.1.1",
    # "jupyter>=1.0.0",
    # "mknotebooks>= 0.8.0",
]


# See https://hatch.pypa.io/latest/config/build/#file-selection for how to
# explicitly include files other than default into the build distributions.

[tool.hatch.version]
source = "uv-dynamic-versioning"

# Ref.: https://github.com/ninoseki/uv-dynamic-versioning/
[tool.uv-dynamic-versioning]
vcs = "git"
style = "pep440"
fallback-version = "0.0.0"