"""Add EPA ecoregion and NEON domain fields

Revision ID: 3c2bd6e56575
Revises: e1b5462e48fa
Create Date: 2025-10-22 18:38:18.836685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c2bd6e56575'
down_revision: Union[str, None] = 'e1b5462e48fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siteMetadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('epa_ecoregion_l1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('epa_ecoregion_l2', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('epa_ecoregion_l3', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('epa_ecoregion_l4', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('neon_domain', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siteMetadata', schema=None) as batch_op:
        batch_op.drop_column('neon_domain')
        batch_op.drop_column('epa_ecoregion_l4')
        batch_op.drop_column('epa_ecoregion_l3')
        batch_op.drop_column('epa_ecoregion_l2')
        batch_op.drop_column('epa_ecoregion_l1')

    # ### end Alembic commands ###
