"""metagenomics testing

Revision ID: 66998be24ab6
Revises: 3c2bd6e56575
Create Date: 2025-11-07 11:54:22.623675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66998be24ab6'
down_revision: Union[str, None] = '3c2bd6e56575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_name', sa.Text(), nullable=False),
    sa.Column('campaign_year', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Metagenomics_AnnotationProduct',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_step', sa.Enum('ReadQcAnalysis', 'MetagenomeAssembly', 'ReadBasedTaxonomyAnalysis', 'MetagenomeAnnotation', 'MagsAnalysis', 'FunctionalAnnotation', 'GenePhylogeny', name='metagenomicssteps'), nullable=True),
    sa.Column('sample_id', sa.UUID(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('annotation_database', sa.Enum('PFAM', 'COG', 'KEGG', name='annotationdatabasetype'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['processedData.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Metagenomics_BinningProduct',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_step', sa.Enum('ReadQcAnalysis', 'MetagenomeAssembly', 'ReadBasedTaxonomyAnalysis', 'MetagenomeAnnotation', 'MagsAnalysis', 'FunctionalAnnotation', 'GenePhylogeny', name='metagenomicssteps'), nullable=True),
    sa.Column('sample_id', sa.UUID(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['processedData.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Metagenomics_GenePhylogenyProduct',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_step', sa.Enum('ReadQcAnalysis', 'MetagenomeAssembly', 'ReadBasedTaxonomyAnalysis', 'MetagenomeAnnotation', 'MagsAnalysis', 'FunctionalAnnotation', 'GenePhylogeny', name='metagenomicssteps'), nullable=True),
    sa.Column('sample_id', sa.UUID(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('gene_family', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['processedData.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('study', sa.Column('campaign_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'study', 'campaign', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # Downgrade not supported
    raise NotImplementedError("Downgrade operations are not supported")
