"""Add EPA ecoregion and NEON domain fields

Revision ID: epa_neon_fields
Revises: e1b5462e48fa
Create Date: 2025-10-22 11:30:44.029850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'epa_neon_fields'
down_revision: Union[str, None] = 'e1b5462e48fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('siteMetadata', sa.Column('epa_ecoregion_l1', sa.Text(), nullable=True))
    op.add_column('siteMetadata', sa.Column('epa_ecoregion_l2', sa.Text(), nullable=True))
    op.add_column('siteMetadata', sa.Column('epa_ecoregion_l3', sa.Text(), nullable=True))
    op.add_column('siteMetadata', sa.Column('epa_ecoregion_l4', sa.Text(), nullable=True))
    op.add_column('siteMetadata', sa.Column('neon_domain', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # Downgrade not supported
    raise NotImplementedError("Downgrade operations are not supported")
