"""test

Revision ID: revision
Revises: e1b5462e48fa
Create Date: 2025-10-14 16:05:22.589065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'revision'
down_revision: Union[str, None] = 'e1b5462e48fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # Downgrade not supported
    raise NotImplementedError("Downgrade operations are not supported")
