"""test

Revision ID: revision
Revises: e1b5462e48fa
Create Date: 2025-10-09 16:34:08.268420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'revision'
down_revision: Union[str, None] = 'e1b5462e48fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alternativeIdentifier')
    op.drop_table('BulkDensityMethod')
    op.drop_table('MetaGenomicsProduct')
    op.drop_table('ElementalAnalysisMethod')
    op.drop_table('custodian')
    op.drop_table('labDevice')
    op.drop_table('WEOMProduct')
    op.drop_table('BulkDensityProduct')
    op.drop_table('personValue')
    op.drop_table('timestampValue')
    op.drop_table('MicrobialBiomassMethod')
    op.drop_table('instrument_alt_id')
    op.drop_table('PhosphorusAnalysisProduct')
    op.drop_table('ontologyClass')
    op.drop_table('IonsAnalysisProduct')
    op.drop_table('XrayComputedTomographyMethod')
    op.drop_table('workflowExecutionFunctionalAnnotation')
    op.drop_table('analysisActivity')
    op.drop_table('LCMS_MetabolomicsMethod')
    op.drop_table('latLongValue')
    op.drop_table('soil')
    op.drop_table('softwareControlledTermValue')
    op.drop_table('metaboliteQuantification')
    op.drop_table('instrumentCustodian')
    op.drop_table('GravimetricWaterContentMethod')
    op.drop_table('EnzymeProduct')
    op.drop_table('textValue')
    op.drop_table('FTICR_AcquisitionMethod')
    op.drop_table('TOC_TN_Method')
    op.drop_table('functionalAnnotationIdentifier')
    op.drop_table('RespirationMethod')
    op.drop_table('changelog')
    op.drop_table('magBin')
    op.drop_table('processedData')
    op.drop_table('MicrobialBiomassProduct')
    op.drop_table('instrument')
    op.drop_table('sampling_activity_site_metadata_link')
    op.drop_table('NitrogenAnalysisProduct')
    op.drop_table('peptideQuantification')
    op.drop_table('ElementalAnalysisProduct')
    op.drop_table('processingSampleLink')
    op.drop_table('workflowExecutionActivity')
    op.drop_table('KuoMethod')
    op.drop_table('zipDownload')
    op.drop_table('containerType')
    op.drop_table('FTICRProduct')
    op.drop_index(op.f('ix_siteMetadata_cache_key'), table_name='siteMetadata')
    op.drop_table('siteMetadata')
    op.drop_table('TomographyProduct')
    op.drop_table('RespirationProduct')
    op.drop_table('sampleProcessing')
    op.drop_table('PH_Method')
    op.drop_table('TextureProduct')
    op.drop_table('GWCMoistureProduct')
    op.drop_table('TextureMethod')
    op.drop_table('MAOMProduct')
    op.drop_table('HydraulicPropertiesMethod')
    op.drop_table('EnzymeActivityMethod')
    op.drop_table('controlledTermValue')
    op.drop_table('pHProduct')
    op.drop_table('instrumentData')
    op.drop_table('conditioningValue')
    op.drop_table('ecoregion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # Downgrade not supported
    raise NotImplementedError("Downgrade operations are not supported")
