// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table ProcessedData {
  id uuid [primary key]

  Note: '''
  '''
}

Table InstrumentData {
  id uuid [primary key]

  Note: '''
  '''
}

Table ProcessedSample {
  id uuid [primary key]

  Note: '''
  '''
}

Table Sample {
  id uuid [primary key]

  Note: '''
  '''
}

Table SamplingActivity {
  id uuid [primary key]

  Note: '''
  '''
}

Table SampleProcessing {
  id uuid [primary key]

  Note: '''
  '''
}

Table AnalysisActivity {
  id uuid [primary key]

  Note: '''
  '''
}

Table WorkflowExecutionActivity {
  id uuid [primary key]

  Note: '''
  '''
}